{
  "hash": "cb9986c1aa69f44e23c010c8ac299532",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Does the Brain’s E:I Balance Really Shape Long-Range Temporal Correlations? Lessons Learned from 3T MRI\"\ntitlerunning: \"\"\nauthors:\n  - name: Lydia Sochan\n    orcid: 0000-0003-2247-6870\n    email: lydiasochan@gmail.com\n    roles:\n      - data curation\n      - formal analysis\n      - investigation\n      - software\n      - visualization\n      - writing - original draft preparation\n    affiliations:\n      - ref: 1\n    degrees:\n      - BMSc\n      - MASc\n  - name: Jessica Archibald\n    orcid: 0000-0001-6651-183X\n    email: jea4025@med.cornell.edu\n    roles:\n      - validation\n      - writing - review & editing\n    affiliations:\n      - ref: 4\n    degrees:\n      - BMSc\n      - MASc\n  - name: Alexander Mark Weber\n    orcid: 0000-0001-7295-0775\n    corresponding: true\n    email: aweber@bcchr.ca\n    roles:\n      - conceptualization\n      - data curation\n      - formal analysis\n      - funding acquisition\n      - investigation\n      - methodology\n      - project administration\n      - resources\n      - supervision\n      - validation\n      - visualization\n      - writing - review & editing\n    affiliations:\n      - ref: 1\n      - ref: 2\n      - ref: 3\n    degrees:\n      - PhD\n      - MSc\naffiliations:\n  - id: 1\n    name: School of Biomedical Engineering, The University of British Columbia, Vancouver, BC, Canada\n  - id: 2\n    name: BC Children's Hospital Research Institute, The University of British Columbia, Vancouver, BC, Canada\n  - id: 3\n    name: Pediatrics, The University of British Columbia, Vancouver, BC, Canada\n  - id: 4\n    name: Department of Radiology, Weill Cornell Medicine, New York, New York, USA\n\nkeywords:\n  - Hurst exponent\n  - long range temporal correlation\n  - excitatory / inhibitory balance\n  - criticality\n  - complex systems\n  - visual task\n  - functional magnetic resnonance imaging\n  - magnetic resonance spectroscopy\n  - functional magnetic resonance spectroscopy\n\nfilters:\n  - authors-block\n\nappendix-style: none\ntbl-cap-location: bottom\nnotebook-links: false\nnumber-sections: true\ncitation:\n  container-title: Unpublished\ndate: last-modified\nbibliography: EIHurst.bib\ncsl: nature.csl\n\ncrossref:\n  fig-title: '**Figure**'\n  tbl-title: '**Table**'\n  title-delim: \"**.**\"\n  custom:\n    - kind: float\n      key: suppfig\n      latex-env: suppfig\n      reference-prefix: '**Figure S**'\n      space-before-numbering: false\n      latex-list-of-description: Supplementary Figure\n    - kind: float\n      key: supptbl\n      latex-env: supptbl\n      reference-prefix: '**Table S**'\n      space-before-numbering: false\n      latex-list-of-description: Supplementary Table \n---\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n# options\nknitr::opts_chunk$set(\n  # fig.width=8, fig.height=5,\n  # out.width=\"50%\",\n  # fig.align=\"center\",\n  echo=FALSE,\n  message=FALSE,\n  warning=FALSE\n  # cache=TRUE\n)\nset.seed(1234) # reproducible\noptions(knitr.kable.NA = '') # how kable handles NA\noptions(reticulate.repl.quiet = TRUE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#libraries\nlibrary(tidyverse) # ggplot2, dplyr, tidyr, readr, purrr, tibble, stringr, forcats\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.1     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(english) # numbers to words\nlibrary(tools) # title-case\nlibrary(patchwork) # figure manipulation\nlibrary(magick) # load images\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLinking to ImageMagick 6.9.12.98\nEnabled features: fontconfig, freetype, fftw, heic, lcms, pango, raw, webp, x11\nDisabled features: cairo, ghostscript, rsvg\nUsing 32 threads\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(ggpubr)\nlibrary(knitr)\n#library(kableExtra)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nload(\"notebooks/results.RData\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRegistered S3 method overwritten by 'lme4':\n  method           from\n  na.action.merMod car \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nformat_p <- function(p, digits = 2) {\n  if (p < 0.01) {\n    \"< 0.01\"\n  } else {\n    format(round(p, digits), nsmall = digits)\n  }\n}\ncapitalize_first <- function(x) {\n  paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))\n} # capitalize first letter\n```\n:::\n\n\n\n\n\n## Abstract {.unnumbered}\n\nA 3T multimodal MR study of healthy adults (n=18; 10 female; 21.3 - 53.4 years) was performed to investigate the relationship between fMRI long-range temporal correlations and excitatory/inhibitory balance (via single voxel magnetic resonance spectroscopy measurements of glutamate and GABA). The study objective was to determine if the Hurst exponent (H) --- an estimate of self-correlation and signal complexity --- of the blood-oxygen-level-dependent signal was correlated with the excitatory-inhibitory (E:I) ratio. E:I has been proposed to serve as a control parameter for brain criticality --- the theory that the brain operates near a critical point between order and disorder, optimizing information processing and adaptability --- which H is believed to be a measure of. Thus, understanding if H and E:I are indeed correlated would clarify this relationship. Moreover, findings in this domain have implications for neurological and neuropsychiatric conditions with disrupted E:I balance, such as autism, schizophrenia, and Alzheimer’s disease. From a practical perspective, H is easier to accurately measure than E:I ratio at 3T MRI. If H can serve as a proxy for E:I, it may serve as a more practical clinical biomarker for this imbalance and for neuroscience research in general. The study collected functional MRI and magnetic resonance spectroscopy data during rest and movie-watching. H and E:I (glutamate/GABA) were not found to be correlated. H was found to increase with movie-watching compared to rest, while E:I did not change between conditions. This study represents the first attempt to investigate this connection *in vivo* in humans. We conclude that, at 3T and with our particular methodologies, no association was found. We end with lessons learned and suggestions for future research.\n\n# Introduction\n\nThe human brain consists of interconnected networks of neurons whose collective activity gives rise to complex behaviors and cognition. In order to understand how neural systems generate this emergent functionality, neuroscience is increasingly using tools and concepts from the science of complexity. Recent advances have led to the emergence of the Critical Brain Hypothesis, which posits that the brain --- across all regions and networks --- operates at a 'critical point', a state where both order and disorder are balanced to enable the most efficient information processing [@decoRestingBrainsNever2013; @beggsBeingCriticalCriticality2012; @barangerChaosComplexityEntropy2000; @bassettUnderstandingComplexityHuman2011; @zimmernWhyBrainCriticality2020; @liangExcitationInhibitionBalance2024; @poilCriticalStateDynamicsAvalanches2012; @lombardiBalanceExcitationInhibition2017; @baumgartenCriticalExcitationinhibitionBalance2019; @bruiningMeasurementExcitationinhibitionRatio2020; @trakoshisIntrinsicExcitationinhibitionImbalance; @gaoInferringSynapticExcitation2017; @tianTheoreticalFoundationsStudying2022; @rubinovNeurobiologicallyRealisticDeterminants2011]. \nIn fact, criticality is perhaps the main way that nature produces stable complex systems [@langtonComputationEdgeChaos1990; @bakHowNatureWorks1996]. When in a critical state, the brain is optimally responsive to both internal and external stimuli while maintaining a balance between stability and instability [@decoRestingBrainsNever2013; @beggsBeingCriticalCriticality2012; @tianTheoreticalFoundationsStudying2022; @rubinovNeurobiologicallyRealisticDeterminants2011]. \n\nCurrently, the most popular theory proposing how the brain achieves this delicate balance --- what is known as the 'control parameter' --- is the excitation-inhibition (E:I) ratio: the balance of excitatory and inhibitory neural activity, often operationalized as the ratio of the primary excitatory and inhibitory neurotransmitters (i.e. glutamate (Glu) and $\\gamma$-aminobutyric acid (GABA)) [@liangExcitationInhibitionBalance2024; @lombardiBalanceExcitationInhibition2017; @baumgartenCriticalExcitationinhibitionBalance2019; @bruiningMeasurementExcitationinhibitionRatio2020; @trakoshisIntrinsicExcitationinhibitionImbalance; @gaoInferringSynapticExcitation2017]. \nThis theory essentially relies on the fact that E:I is a primary driver of the signal-to-noise ratio (SNR) of neuronal signalling, and hence could drive transitions between order and disorder [@liangExcitationInhibitionBalance2024; @rubensteinModelAutismIncreased2003]. Thus, the E:I theory of criticality posits that altering the E:I ratio would allow for movement between sub- and super-critical states [@liangExcitationInhibitionBalance2024]. When excitation is perfectly balanced with inhibition, the system is at a critical point, but if either excitation or inhibition are favoured, the system can become overly noisy (excess excitation) or overly controlled (excess inhibition), respectively [@liangExcitationInhibitionBalance2024]. Thus, the relationship between E:I balance and large-scale brain dynamics offers a promising link between synaptic physiology and macroscopic neural computation, and for elucidating fundamental neural computational principles. Furthermore, understanding this relationship could hold great clinical relevance, as disruptions in E:I homeostasis have been implicated in multiple neuropsychiatric and neurodevelopmental disorders --- including autism, schizophrenia, and Alzheimer's disease --- making this an important target for biomarker development and therapeutic intervention [@bruiningMeasurementExcitationinhibitionRatio2020; @lauterbornIncreasedExcitatoryInhibitory2021; @sohalExcitationinhibitionBalanceFramework2019].\n\n*In vivo* measurement of brain criticality can be achieved using several available methods, as systems near a critical state often exhibit fractal-like fluctuations or scale-invariance [@munozColloquiumCriticalityDynamical2018]. Scale-invariance has been observed extensively across various neuronal spatio-temporal scales, from dendritic branching structures [@casertaDeterminationFractalDimension1995] in the spatial domain, to neurotransmitter release [@lowenQuantalNeurotransmitterSecretion1997], neuronal firing rates [@mazzoniDynamicsSpontaneousActivity2007], local field potentials [@bedardMacroscopicModelsLocal2009], electroencephalography (EEG) [@bullmoreFractalAnalysisElectroencephalographic1994] and functional magnetic resonance imaging (fMRI) --- which measures the blood oxygen level-dependent (BOLD) signal [@zarahnEmpiricalAnalysesBOLD1997; @fadiliWaveletGeneralizedLeastSquares2002; @campbellMonofractalAnalysisFunctional2022] --- in the time domain. This fractal structure can be quantified by assessing the signal's long-range temporal correlations (LRTC), which reflect the persistence or memory in a time series, where future values are statistically related to past values over long extended periods. The Hurst exponent (H) is a useful measure for evaluating LRTC [@ekeFractalCharacterizationComplexity2002; @campbellMonofractalAnalysisFunctional2022]. An H value between 0.5 and 1 indicates a long-range positive correlation, with large values being followed by large values and small values by small ones. Conversely, an H exponent value between 0 and 0.5 indicates a long-range negative correlation, where large values are likely to be followed by small ones and vice versa. An H value of 0.5 is uncorrelated random noise [@hurstLongTermStorageCapacity1951].\n\nH has emerged as a valuable tool in neuroscience and clinical research. Typically, H values reported in adult brains are above 0.5, with higher H values in grey matter than white matter or cerebrospinal fluid [@dongHurstExponentAnalysis2018; @winkMonofractalMultifractalDynamics2008]. Some key findings from neuroscience research include: a decrease in H during task performance [@ciuciuInterplayFunctionalConnectivity2014; @heScaleFreePropertiesFunctional2011]; an increase in H during movie watching in the visual resting state network [@campbellFractalBasedAnalysisFMRI2022]; negative correlations with task novelty and difficulty [@churchillSuppressionScalefreeFMRI2016]; increases with age in the frontal and parietal lobes [@dongHurstExponentAnalysis2018], and hippocampus [@winkAgeCholinergicEffects2006]; decreases with age in the insula, and limbic, occipital and temporal lobes [@dongHurstExponentAnalysis2018]; and H < 0.5 in preterm infants [@mellaTemporalComplexityBOLDsignal2024]. For a more in depth review, see Campbell et al. (2022) [@campbellMonofractalAnalysisFunctional2022]. In terms of clinical findings, abnormal H values have been identified in Alzheimer's disease (AD) [@maximFractionalGaussianNoise2005; @warsiCorrelatingBrainBlood2012], autism [@donaTemporalFractalAnalysis2017; @laiShiftRandomnessBrain2010; @linkeAlteredDevelopmentHurst2024; @uscatescuUsingExcitationInhibition2023], mild traumatic brain injury [@donaFractalAnalysisBrain2017], major depressive disorder [@weiIdentifyingMajorDepressive2013; @jingIdentifyingCurrentRemitted2017] and schizophrenia [@sokunbiNonlinearComplexityAnalysis2014; @uscatescuUsingExcitationInhibition2023]. Crucially, these same disorders have been associated with imbalances in E:I [@lauterbornIncreasedExcitatoryInhibitory2021; @vicovarelaExcitatoryinhibitoryImbalanceAlzheimers2019; @sohalExcitationinhibitionBalanceFramework2019; @uzunovaExcitatoryInhibitoryImbalance2016; @bruiningMeasurementExcitationinhibitionRatio2020; @pagePrefrontalExcitatoryInhibitory2019; @kangInterplayMentalDisorder2019].\n\nIn addition to its implications for the critical brain hypothesis, establishing a connection between E:I and H could facilitate simpler estimation of excitatory and inhibitory neurotransmitters, as precise measurement of E:I is technically challenging [@ajramContribution1HMagnetic2019]. Currently, magnetic resonance spectroscopy (MRS) is the only non-invasive method for *in vivo* assessment of the Glu/GABA ratio (excitatory to inhibitory neurotransmitters) in humans [@stanleyFunctionalMagneticResonance2018; @harrisEdited1Magnetic2017]. Unfortunately, MRS suffers from limited spatial and temporal resolution, with single-voxel spectrosopy sizes between 20 and 27 cm^3^, and scan times between 5-10 minutes [@gaoInferringSynapticExcitation2017; @ajramContribution1HMagnetic2019; @stanleyFunctionalMagneticResonance2018]. In addition, quantification of GABA at 3T necessitates the use of a specialized J-difference spectral-editing sequence (such as MEGA-PRESS), in order to isolate GABA (at 3 ppm, 2.3 ppm, and 1.9 ppm) from overlapping peaks (e.g. creatine and glutamate) [@peekComprehensiveGuideMEGAPRESS2023]. The need for this additional sequence therefore reduces the temporal resolution further. If H could function as a substitute for E:I, it could simplify the estimation of E:I.\n\nBeyond clinical observations suggesting that both H and E:I imbalance are altered in neuropsychiatric conditions, several studies have attempted to show that critical-state dynamics emerge when excitation and inhibition are balanced. Indirect evidence comes from pharmacological manipulation of GABAergic neurotransmission, which has been shown to change the strength of LRTC *in vitro* [@poilFastNetworkOscillations2011] and in the beta-frequency range in humans using EEG [@montoEpileptogenicNeocorticalNetworks2007]; and to eliminate the power-law scaling of neuronal avalanches in rats [@beggsNeuronalAvalanchesNeocortical2003; @gireeshNeuronalAvalanchesOrganize2008; @yangMaximalVariabilityPhase2012].\nMore direct efforts linking H and E:I have mostly relied on computational models or animal studies [@liangExcitationInhibitionBalance2024; @poilCriticalStateDynamicsAvalanches2012; @lombardiBalanceExcitationInhibition2017; @baumgartenCriticalExcitationinhibitionBalance2019; @bruiningMeasurementExcitationinhibitionRatio2020; @trakoshisIntrinsicExcitationinhibitionImbalance; @gaoInferringSynapticExcitation2017], and the results remain inconsistent, ranging from positive to negative or even U-shaped associations. These discrepancies may reflect differences in model systems (e.g., animal vs. computer simulations), methodological choices (such as how H or E:I are estimated), or may represent counter evidence against the theory that these measures are systematically related. Indeed, other theories for how the brain maintains criticality exist, such as neuromodulator regulation [@obyrneHowCriticalBrain2022; @plenzSelfOrganizedCriticalityBrain2021; @avramieaRegulationCriticalBrain2023] or synaptic plasticity [@zeraatiSelfOrganizationCriticalitySynaptic2021; @ikedaEmergentFunctionsNoisedriven2025], to name a few. \nDespite the lack of direct evidence, several recent human studies have used fMRI-derived H as a direct proxy for E:I balance [@linkeAlteredDevelopmentHurst2024; @xiePharmacoresistantTemporalLobe2024; @uscatescuUsingExcitationInhibition2023; @fotiadisMyelinationExcitationinhibitionBalance2023]; yet, no study to date has tested the empirical relationship between H and neurochemical estimates of E:I (e.g., Glu/GABA ratio) *in vivo* in humans. \n\nThe theory that E:I serves as the primary control parameter governing H --- and, by extension, brain criticality --- offers a framework with clear, falsifiable predictions that can be directly tested.\nSpecifically, if this framework holds, E:I and H should covary systematically in the human brain across individuals, age, brain regions, and cognitive states. \nTo empirically test this prediction, the present study examined the E:I–Hurst relationship in the human visual cortex during rest and naturalistic movie-watching. \nAlthough a single condition would be sufficient to test the correlation between E:I and H, we included two conditions to broaden the dynamic range of neural and neurochemical measures --- thereby increasing our sensitivity to detect a correlation --- and to provide validation that our metrics behave as expected across qualitatively different brain states.\nNaturalistic movie-watching is known to reliably engage the visual cortex with complex, temporally structured input, making it a useful condition for probing changes in the temporal dynamics of neural activity [@vanderwalMoviesMagnetNaturalistic2019; @campbellFractalBasedAnalysisFMRI2022]. Prior work from our group has shown that H values increased during movie-watching compared to rest [@campbellFractalBasedAnalysisFMRI2022], while work from others have found changes in Glu and GABA with sustained visual stimulation [@linInvestigatingMetabolicChanges2012; @martinez-maestroDynamicMetabolicChanges2019; @saucedoChangesGABAGlutamate; @kurcyusOppositeDynamicsGABA2018]. We hypothesized that H and Glu would increase during movie-watching [@campbellFractalBasedAnalysisFMRI2022; @linInvestigatingMetabolicChanges2012; @martinez-maestroDynamicMetabolicChanges2019], that GABA would decrease [@saucedoChangesGABAGlutamate; @kurcyusOppositeDynamicsGABA2018], and that H would be positively correlated with E:I in both conditions [@gaoInferringSynapticExcitation2017].\n\n# Methods\n\n## Participants\n\nTwenty-seven healthy adult participants were recruited to the study. One participant was not scanned due to claustrophobia while in the scanner. After our analysis and performing quality assurance (see below for details), a further eight participants were removed, leaving eighteen final participants, between the ages of 21.3 and 53.4 (mean age ± sd: 29.6 ± 8.7 years; 8 males). Sex, handedness and date of birth were recorded on the day of the scan. \n\n## Ethics Statement\n\nWritten informed consent was obtained from all participants. Ethics approval was granted by the Clinical Research Ethics Board at the University of British Columbia and BC Children's & Women's Hospital (H21-02686). \n\n## Scanning Procedure\n\nAfter two anatomical sequences were acquired, participants were instructed to visually fixate on a cross-hair for 24 minutes (see @tbl-mriacq and below for more details). During this period, an fMRI, single-voxel semi Localization by Adiabatic SElective Refocusing (sLASER) [@ozShortechoSingleshotFullintensity2011], and single-voxel MEscher-Garwood Point-REsolved SpectroScopy (MEGA-PRESS) [@mescherSimultaneousVivoSpectral1998] sequences were acquired (see @fig-method A and @sec-mriacq). Next, participants were instructed to watch a nature documentary (Our Planet (2019), Episode 3, “Jungles” [@cordeyJungles2019]) for 24 minutes.  During this period, another set of fMRI, sLASER, and MEGA-PRESS sequences were acquired. See @fig-method B for a visual representation of the scanning protocol. Total scan duration was approximately 1 hour of uninterrupted scanning (i.e. subjects were not removed from the scanner). All participants followed the same order of conditions: rest then movie; all participants saw the same movie segment, beginning at the same time during the scan.\n\n\n\n\n\n::: {#cell-fig-method .cell}\n\n```{.r .cell-code .hidden}\nlayout=\"\n  #AA#\n  BBBB\n  \"\n\nfmrimrs <- image_read('../Figures/StudyDesign/studydesign_fmri_mrs.png')\nfmrimrs_dim <- image_info(fmrimrs)\nfmrimrs <- ggplot() + background_image(fmrimrs) + theme_void() #+ theme(aspect.ratio = fmrimrs_dim$height / fmrimrs_dim$width)\n\nstudydesign <- image_read('../Figures/StudyDesign/StudyDesign.png')\nstudydesign <- ggplot() + background_image(studydesign) + theme_void()\n# p <- (fmrimrs + plot_spacer()) / studydesign\np <- fmrimrs + studydesign + plot_layout(design = layout)\n# p + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\np + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![**Overview of the MRI acquisition protocol.** A) fMRI coverage was across the whole-brain (example coverage in red). MRS voxels were placed in the visual cortex (blue). Background image is of a T1w acquisition from a sample subject. Figure was inspired by Ip et al. (2017) [@ipCombinedFMRIMRSAcquires2017]. B) fMRI, sLASER, and MEGA-PRESS were acquired first with participants looking at a white cross for 24 minutes. Next, the same sequences were acquired with the participants viewing a nature documentary for an identical period of time.](index_files/figure-docx/fig-method-1.png){#fig-method}\n:::\n:::\n\n\n\n\n\n## Acquisition Details {#sec-mriacq}\n\nScans were performed at BC Children’s Hospital MRI Research Facility on a 3.0 Tesla GE Discovery MR750 scanner (scanner software version: DV26.0_R03) with a Nova Medical 32 channel head coil. Participants changed into scrubs and were screened by an MRI technologist. Participants were given wax earplugs and a fiducial was placed on their left temple. Participants were provided with an audio headset and blanket once lying down on the scanner bed. Since visual stimuli were rear-projected, position and angle of mirror above patient eyes was adjusted for optimal movie viewing. \n\nThe following MRI scans were acquired. A 3D T1-weighted sagittal fast spoiled gradient echo (FSPGR) sequence;\na 3D T2-weighted sagittal CUBE;\na 2D echo-planar imaging (EPI) multi-echo gradient-echo fMRI sequence;\na single-voxel MEGA-PRESS sequence with CHESS (CHEmical Shift Selective saturation) water suppression;\nand a single-voxel sLASER sequence with VAPOR (VAriable Power and Optimized Relaxations) water suppression. Details are listed in @tbl-mriacq.\n\n| Sequence                        | TE (ms)        | TR (ms)    | Flip Angle | FOV            | Slice Thickness (mm) | In-Plane Resolution (mm²) | Other Parameters                   | Time (mins) |\n|---------------------------------|---------------|------------|------------|----------------|----------------------|----------------------------|-------------------------------------|----|\n| 3D T1-weighted FSPGR        | 2.176         | 7.216      | 12         | 256 × 256      | 0.9                  | 0.9375 × 0.9375           | -                           | 5 |\n| 3D T2-weighted CUBE         | 75.242        | 2,504.0    | 90          | 256 x 256       | 0.9                  | 0.9375 × 0.9375          | - | 4 |\n| 2D EPI Multi-Echo fMRI      | 12.2, 35.352, 58.504 | 1,500 | 52         | 64 x 64        | 3.6                  | 3.5938 × 3.5938          | Acceleration factor = 6    | 12 |\n| sLASER                      | 35            | 2,000      | 90         | -      | 28.0                    | 28.0 x 28.0           | Transients = 128*; Spectral width = 5,000 Hz; Data points = 4,096 | 4 |\n| MEGA-PRESS                  | 68            | 1,800      | 90         | -      | 28.0                    | 28.0 x 28.0           | Transients = 128 ON, 128 OFF; Spectral width = 5,000 Hz; Data points = 4,096 | 8 |\n\n: **Summary of MRI acquisition details** TE = echo time; TR = repetition time; FOV = field of view; FSPGD = fast spoiled gradient-echo; CUBE = a GE acronym; EPI = echo-planar imaging; fMRI = functional magnetic resonance imaging; sLASER = semi localization by adiabatic selective refocusing; MEGA-PRESS = Mescher-Garwood point-resolved spectroscopy. *Note, the GE semi-LASER sequence averaged the 128 transients into groups of 4, each with 32 transients, before being saved as raw P-file.  {#tbl-mriacq}\n\nFor both MRS sequences, the voxel size was set to 2.8 x 2.8 x 2.8 cm^3^. MRS voxels were rotated and placed in the occipital lobe, aligned along the calcarine fissure, using the high resolution T1w sequence as anatomical guide. Voxel placement was set once at the beginning and copied for the remaining MRS sequences. Glutamate was quantified from semi-LASER acquisitions as it offers the highest quality spectra for unedited metabolites [@wilsonMethodologicalConsensusClinical2019]. The GE semi-LASER sequence automatically aligned and averaged every 32 transients, resulting in 4 averaged transients to process. GABA was measured using MEGA-PRESS, which applies frequency-selective editing pulses to isolate GABA from overlapping signals [@peekComprehensiveGuideMEGAPRESS2023]. This dual-sequence approach is standard in the field and reflects the differing spectral requirements of each metabolite [@vanveenendaalGlutamateQuantificationPRESS2018]. Finally, blip-up and blip-down spin-echo versions of the fMRI sequence were acquired at the end to estimate the B0 non-uniformity map for fMRI phase distortion correction.\n\n## Image Processing\n\nOur full image processing pipeline has been can be accessed from our Github account page: [github.com/WeberLab/EI_Hurst_Analysis](https://github.com/WeberLab/EI_Hurst_Analysis)\n\nImages were downloaded offline from the scanner in raw Digital Imaging and Communications in Medicine (DICOM) format. DICOM files were then converted to Neuroimaging Informatics Technology Initiative (NIfTI) using Chris Rorden’s `dcm2niix` [@liFirstStepNeuroimaging2016] (v1.0.20211006) and then to Brain Imaging Data Structure (BIDS) [@gorgolewskiBrainImagingData2016] format using `dcm2bids ` [@boreDcm2Bids2023] (v2.1.6). MRS files were downloaded as raw P files.\n\n### Structural Images\n\nThe T1w image was corrected for intensity non-uniformity with `N4BiasFieldCorrection` [@tustisonN4ITKImprovedN32010] (`ANTs` [@avantsSymmetricDiffeomorphicImage2008]; v2.3.335) to be used as a T1w-reference for the rest of the workflow. The T1w-reference was skull-stripped using a `Nipype` [@gorgolewskiNipypeFlexibleLightweight2016] implementation of `antsBrainExtraction.sh` from `ANTs`; `OASIS30ANTs` was used as a target template. `Fast` [@zhangSegmentationBrainMR2001] (`FSL` [@smithAdvancesFunctionalStructural2004] v.6.0.5.1:57b01774, RRID: SCR\\_002823) was used for brain tissue segmentation into cerebrospinal fluid (CSF), white matter (WM), and gray matter (GM). Brain surfaces were reconstructed with `recon-all` [@daleCorticalSurfacebasedAnalysis1999] (`FreeSurfer` [@daleCorticalSurfacebasedAnalysis1999] 7.3.2, RRID: SCR\\_001847). The previously-estimated brain mask was refined with `Mindboggle` [@kleinMindbogglingMorphometryHuman2017] (RRID:SCR\\_002438) to reconcile ANTs-derived and FreeSurfer-derived segmentations of cortical GM. `AntsRegistration` [@avantsSymmetricDiffeomorphicImage2008] (`ANTs` 2.3.3) was used to perform volume-based spatial normalization to two standard spaces: MNI152NLin2009cAsym and MNI152NLin6Asym. Normalization used brain-extracted versions of both T1w reference and T1w template. \n\n### fMRI\n\nUsing `fMRIPrep` [@estebanFMRIPrepRobustPreprocessing2019], the shortest echo of the BOLD run was used to generate a reference volume (both skull-stripped and skull-included). Head-motion parameters with respect to the BOLD reference (transformation matrices as well as six corresponding rotation and translation parameters) were estimated before spatiotemporal filtering using `mcflirt` [@jenkinsonImprovedOptimizationRobust2002] (`FSL` v6.0.5.1:57b01774). The fieldmap was aligned with rigid registration to the target EPI reference run. Field coefficients were mapped to the reference EPI using the transform. BOLD runs were slice-time corrected to 643 ms (half of slice acquisition range of 0-1290 ms) using `3dTshift` from `AFNI` [@coxAFNISoftwareAnalysis1996] (RRIS: SCR_005927). To estimate T2* map from preprocessed EPI echoes, a voxel-wise fitting was performed by fitting the maximum number of echoes with reliable echoes in a particular voxel to a monoexponential signal decay model with nonlinear regression. Initial values were T2*/S0 estimates from a log-linear regression fit. This calculated T2* map was then used to optimally combine preprocessed BOLD across echoes using the method by Posse et al. (1999) [@posseEnhancementBOLDcontrastSensitivity1999]. The generated BOLD reference was then co-registered (6 degrees of freedom) to the T1w reference with `bbregister` (`FreeSurfer` [@daleCorticalSurfacebasedAnalysis1999]) using boundary-based registration. First, a reference volume and its skull-stripped equivalent were generated with `fMRIPrep`. Confounding time series were calculated from preprocessed BOLD: framewise displacement (FD), DVARS, and three region-wise global signals. `Tedana` [@dupreTEdependentAnalysisMultiecho2021] was then used to denoise the data by decomposing the multi-echo BOLD data via principal component analysis (PCA) and independent component analysis (ICA). The resulting components are automatically analyzed to determine whether they are TE-dependent or -independent. TE-dependent components were classified as BOLD, while TE-independent components were classified as non-BOLD and were discarded as part of data cleaning.\n\nParticipants were excluded from further analysis if their mean FD was > 0.15 mm.\n\n## MRS\n\nsLASER data were processed using `Osprey` [@oeltzschnerOspreyOpenSourceProcessing2020] (v2.9.5) and fit via the embedded `LCModel` (v6.3-1N) wrapper [@provencherAutomaticQuantitationLocalized2001]. \nBecause of substantial overlap among Glu and Gln resonances [@pasantaFunctionalMRSStudies2023; @ramadanGlutamateGlutamineReview2013], in order to avoid errors in spectral assignment --- especially since it is controversial whether Glu can reliably be separated from Gln at 3T [@zollnerComparisonDifferentLinearcombination2021; @zollnerComparisonLinearCombination2022] --- we report Glx (Glu+ Glu) as the primary outcome measure.  Individual Glu estimates are provided in Supplementary Materials @supptbl-metabolites, alongside all other quantified metabolites.\nSeveral Osprey functions were modified to accommodate scanner-specific features of the GE implementation, where individual transients had been averaged by the scanner into four sub-spectra prior to export. These changes primarily affected `GEload.m` to correct water-scaling inconsistencies. RF coil combination was performed using generalized least squares (GLS) weighting, following An et al. (2013) [@anCombinationMultichannelSinglevoxel2013; @bouchardNoiseDecorrelationCoil2025].\n\nMEGA-PRESS data were processed with `Osprey`, and the difference of the ON and OFF sequences were fit the `LCModel` algorithm. \nDue to the J-editing sequence of MEGA-PRESS, a challenge of GABA quantification is macromolecule quantification [@harrisSpectralEditingMeasurementsGABA2015]. As a result, we report GABA+, a measure which co-reports GABA with macromolecules. Macromolecules (MM) are expected to account for approximately 45% of the GABA+ signal [@harrisSpectralEditingMeasurementsGABA2015]. While a macromolecule-suppressed estimate of GABA seems ideal, a recent 25-site and multi-vendor study conducted at 3T found that GABA+ showed much lower coefficient of variation than MM-suppressed GABA, meaning that GABA+ is more consistent across research sites and MRI vendors (i.e., Philips, GE, Siemens) [@mikkelsenBigGABAII2019]. Moreover, GABA+ shows greater reliability for both creatine-referenced and water-suppressed estimates [@mikkelsenBigGABAEdited2017; @mikkelsenBigGABAII2019]. MM-suppressed GABA and GABA+ estimates are also correlated, albeit weakly- to moderately-so [@harrisSpectralEditingMeasurementsGABA2015; @mikkelsenBigGABAII2019; @mikkelsenBigGABAEdited2017]. Consequently, we report GABA+ to allow for easier comparison of our results to other studies as well as reproducibility. All metabolite values, including GABA, are reported in the Supplementary Materials @supptbl-megapressmetabs.\n\nMRS voxels were co-registered to the T1w reference image and segmented by `SPM12` [@fristonStatisticalParametricMapping2007] into CSF, GM, and WM.\nsLASER and MEGA-PRESS data were were water-scaled as well as tissue- and relaxation-corrected by the Gasparovic et al. (2006) method [@gasparovicUseTissueWater2006]. Concentrations are reported in millimoles.\nFull width half-maximum (FWHM) of the single-Lorentzian fit of the water peak, signal-to-noise (SNR) ratio of the creatine signal, frequency shift, and Cramer-Rao lower bounds (CRLB) were calculated for quality assurance purposes.\n`Osprey` basis sets were used for linear combination. Metabolites included for both basis sets were: Asc, Asp, Cr, CrCH2, EA, GABA, GPC, GSH, Gln, Glu, Gly, H2O, Lac, NAA, NAAG, PCh, PCr, PE, Ser, Tau, mI, and sI. Excitatory-inhibitory ratio (E:I) was calculated as [Glx from sLASER]/[GABA+ from MEGA-PRESS], a common practice to report E:I using MRS [@rideauxNoBalanceGlutamate+glutamine2021].\n<!-- TODO: Show Glx from sLASER is correlated with Glx from MEGA-PRESS --> \n\nParticipants were excluded from further analysis if any of their MRS scans had a water peak FWHM > 10 [@juchemB0ShimmingVivo2021]. \n\nTo quantify the inter-subject consistency across the MRS masks, we computed a consensus mask using majority voting and calculated the mean Dice coefficient between each individual mask and the consensus.\n\n### Re-analysis using Gannet\n\nGlutamate and GABA were acquired using different MRS sequences and in separate blocks during the same scan session. While acquisitions were closely timed and performed under similar conditions, we cannot fully exclude the possibility of session-related variability affecting E:I ratio estimates. Therefore, we re-ran our analysis using the Glx and GABA+ values from the MEGA-PRESS sequence alone using `Gannet` [@eddenGannetBatchprocessingTool2014] (v3.3.0). \n\n## Hurst Exponent Calculation\n\nHurst exponent was calculated from the power spectrum density (PSD) of the BOLD signal. A log-log plot was used, where log power was plotted against log frequency; generally, if a log-log plot results in a linear relationship, it is assumed that the mean slope of this line represents the power-law exponent [@zimmernWhyBrainCriticality2020]. A PSD shows the distribution of signal variance (‘power’) across frequencies. Complex signals are classified into two categories: fractional Gaussian noise (fGn) and fractional Brownian motion (fBm) [@duffPowerSpectralDensity2008; @ekeFractalCharacterizationComplexity2002]. The former is a stationary signal (i.e., does not vary over time), while the latter is non-stationary with stationary increments [@ekeFractalCharacterizationComplexity2002]. Most physiological signals consist of fBm, but fMRI BOLD is typically conceptualized as fGn once motion-corrected; otherwise put, unprocessed BOLD signal is initially fBm which is converted to fGn with appropriate processing [@bullmoreWaveletsFunctionalMagnetic2004]. fBm and fGn require distinct H calculation methods [@ekeFractalCharacterizationComplexity2002]. PSD was estimated using Welch’s method [@welchUseFastFourier1967] from the Python `Scipy.Signal` library [@virtanenSciPy10Fundamental2020]. Data were divided into 8 windows of 50% overlap and averaged within each window, as is standard [@rubinOptimizingComplexityMeasures2013]. Welch's method was selected based on prior comparisons with other Hurst exponent algorithms, which found it to perform best across all evaluation criteria [@rubinOptimizingComplexityMeasures2013]. The spectral index, $\\beta$, was calculated from the full frequency spectrum. The spectral index was then converted to H using the following equation [@ekeFractalCharacterizationComplexity2002; @schaeferComparativeAnalysisSpectral2014]:\n\n$$\nH = \\frac{1 + \\beta}{2}\n$$\n\nSince it cannot be assumed that all fBm is removed from the signal, we employed the ‘extended Hurst’ (H’) concept in this study: for 0 < H < 1, the signal is understood as fGn, while for 1 < H < 2, the signal is understood to be fBm [@campbellFractalBasedAnalysisFMRI2022; @hartmannRealtimeFractalSignal2013; @ekePhysiologicalTimeSeries2000]. More generally, it is assumed that when 0.5 < H < 1.5, the signal displays 1/f behaviour [@zimmernWhyBrainCriticality2020]. H was calculated for all voxels in the brain of each subject. A brain mask was then applied which included only GM and the region of the MRS voxel in the visual cortex. H was averaged across the brain mask area, using only non-zero voxels.\n\n## Statistics\n\nAll statistical analyses were performed using `R` [@rcoreteamLanguageEnvironmentStatistical2021] (v4.5.1) and `RStudio`. \n\nA linear mixed-effect model was used to test for the correlation of H and E:I, with H as the dependent variable, Glx/GABA+ as the primary predictor of interest, and Condition (rest vs. movie) as a fixed effect. Mean FD, FWHM(sLASER), FWHM(MEGA-PRESS), Frequency Shift (sLASER), Frequency Shift (MEGA-PRESS) were included as covariates, and subjects were modeled as random effects:\n\n$$\n\\begin{aligned}\n\\mathrm{H} \\sim\\;& \\frac{\\mathrm{Glx}}{\\mathrm{GABA\\text{+}}} + \\mathrm{Condition} +\\mathrm{meanFD} \\\\ \n& + \\mathrm{FWHM_{sLASER}} + \\mathrm{FWHM_{MEGA\\text{-}PRESS}} \\\\\n& + \\mathrm{FreqShift_{sLASER}} + \\mathrm{FreqShift_{MEGA\\text{-}PRESS}} \\\\\n& + (1 | \\mathrm{Subject})\n\\end{aligned}\n$$\n\nA post-hoc calculation of the power of the model was calculated using `powerSim` from the `simr` package using 1,000 simulations.\n\nExploratory post hoc analyses were then performed. Difference in the means of H, Glx, and GABA+ between rest and movie conditions were assessed using paired Student’s t-tests [@studentProbableErrorMean1908]. Correlations between H and Glx, GABA+ and E:I were calculated using Pearson’s method [@freedmanStatistics2007].\n\n# Results\n\n## Participant Demographics\n\nTwenty-seven participants were originally recruited for the study. Twenty-six of these participants were successfully scanned, but one participant experienced claustrophobia and chose not to continue. Of the remaining 26 participants, 18 were included in the final analysis: three were removed due to low MRS quality (FWHM > 10) and five were removed due to low fMRI quality (mean FD > 0.15 mm). See @fig-partflow.\n\n![**Flowchart of participant, recruitment, scanning and exclusion**. The number of participants at each stage is indicated within each node. Participants were excluded based on MRS FWHM and fMRI Mean FD thresholds, resulting in 18 participants included in the final analysis](./images/ParticipantFlow.png){#fig-partflow}\n\nThe final study sample included 8 males and 10 females between ages 21.3 and 53.4, with a mean age and standard deviation of  29.6 ± 8.7 years.\n\n## Data Summary\n\nAn average of all MRS voxel placements can be seen in @fig-mrsquality A, and a sample of the `Osprey` sLASER and MEGA-PRESS spectrum fits at rest can be seen in @fig-mrsquality B and C, respectively. The mean consensus-based inter-subject Dice score for MRS voxel placements was 0.77 $\\pm$ 0.14 (range: [0.35, 0.95]).\n\n\n\n\n\n::: {#cell-fig-mrsquality .cell}\n\n```{.r .cell-code .hidden}\nlayout <- \"\n  AAAA\n  AAAA\n  BBCC\n  BBCC\n  \"\n\nmrsvoxel <- image_read(\"./images/MRSVoxelAverage.png\") # From Figures.ipynb\nmrsvoxel <- ggplot() + background_image(mrsvoxel) + theme_void() #+ coord_fixed()\n\nospreyslaser <- image_read(\"./Data/sub-Pilot01_metab_A_model.jpg\")\nospreyslaser_dim <- image_info(ospreyslaser)\nospreyslaser <- ggplot() + background_image(ospreyslaser) + theme_void() #+ coord_fixed() # + theme(aspect.ratio = ospreyslaser_dim$height / ospreyslaser_dim$width)\n\nospreymegapress <- image_read(\"./Data/sub-Pilot01_metab_diff1_model.jpg\")\nospreymegapress_dim <- image_info(ospreymegapress)\nospreymegapress <- ggplot() + background_image(ospreymegapress) + theme_void() #+ coord_fixed()\n  # theme(aspect.ratio = ospreymegapress_dim$height / ospreymegapress_dim$width)\n# p1 <- free(mrsvoxel) + ospreyslaser + ospreymegapress + glu_FWHM_plot\np1 <- free(mrsvoxel) + free(ospreyslaser) + free(ospreymegapress) + \n  plot_layout(design = layout)\np1 + plot_annotation(tag_levels = \"A\") + theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output-display}\n![**MRS data quality** A) Average MRS location. Colored overlay of the average voxel location across all nineteen participants, from 0 (black) to 1 (white). Brighter yellow represents voxel locations shared by all participants, while darker purple represents voxel locations unique to participants. MRS voxels were registered to MNI space and averaged. Underlay is T1w MNI152 at 0.5 mm resolution. B) Sample Osprey sLASER Spectrum. Red spectrum indicates overall model fit. Model fits for individual metabolites are shown in blue below overall fit. C) Sample Osprey MEGA-PRESS Spectrum. Yellow spectrum indicates overall model fit. Model fits for individual metabolites are shown in blue below overall fit.](index_files/figure-docx/fig-mrsquality-1.png){#fig-mrsquality}\n:::\n:::\n\n\n\n\n\nAverage water FWHM, creatine SNR, and frequency shift are reported in Supplementary Material @supptbl-quality.\n\nAverage voxel rotation along the x-axis, along with average tissue fractions are reported in Supplementary Material @supptbl-singlevoxel.\n\nA sample of the combined grey-matter and MRS voxel mask used to average H values, along with a sample Hurst exponent map, and sample fits for H calculation during rest can be found in @fig-hurstsamp A, B, and C, respectively.\n\n\n\n\n\n::: {#cell-fig-hurstsamp .cell}\n\n```{.r .cell-code .hidden}\nlayout = \"\n  AAA\n  BBB\n  #C#\n  \"\n\nfmrimask <- image_read(\"./images/SampleMask.png\")\n# add white space to the right\nfmrimask_dim <- image_info(fmrimask)\nwhite <- image_blank(fmrimask_dim$width/8.3, fmrimask_dim$height, \"white\")\nfmrimask <- c(fmrimask, white)\nfmrimask <- image_append(fmrimask)\nfmrimask <- ggplot() + background_image(fmrimask) + theme_void()\nhurstsamp <- image_read(\"./images/HurstSample.png\")\nhurstsamp_dim <- image_info(hurstsamp)\nhurstsamp <- ggplot() + background_image(hurstsamp) + theme_void()\npsdplot <- image_read(\"./images/PSDs.png\")\npsdplot_dim <- image_info(psdplot)\npsdplot <- ggplot() + background_image(psdplot) + theme_void() #+ theme(aspect.ratio = psdplot_dim$height / psdplot_dim$width)\n\nfmrimask + hurstsamp + psdplot + \n  plot_layout(design = layout) +\n  plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![**fMRI data quality.** A) sample fMRI grey-matter mask within the MRS voxel. Background: a sample coronal, sagittal, and axial slice is displayed of the mean fMRI scan from the rest acquisition. Foreground: the greymatter/MRS mask used to calculate mean H. B) Sample H map for whole brain. Coronal, sagittal, and axial views of are shown, colour-coded by H values. Colour-coding shows evident tissue differentiation by H value (i.e., gray matter (red), white matter (light red), and cerebrospinal fluid (white)). C) Sample PSD spectrum. All participants' PSD spectrums during rest are plotted using light grey lines. Mean PSD is plotted in solid red Mean linear regression line is plotted in dashed blue. H for each participant was calculated from the slope of their mean linear regression line. ](index_files/figure-docx/fig-hurstsamp-1.png){#fig-hurstsamp}\n:::\n:::\n\n\n\n\n\n@fig-averagehurst shows the average Hurst maps during rest and movie watching.\n\n![**Average Hurst maps for rest and movie conditions** Group averaged maps of the Hurst exponent computed to visualize whole-brain patterns across sessions: rest (top) and movie watching (bottom.)](./images/RestMovieHurstAverage.png){#fig-averagehurst width=80%}\n\n## Linear-mixed effects model: H and E:I\n\nTo examine the relationship between H and E:I, we ran a linear mixed-effects model. \nThe model's total explanatory power was substantial (conditional r^2^ = 0.79), with fixed effects (marginal r^2^) equal to 0.22. The model's intercept, corresponding to EI = 0, Condition = Movie, FWHM~sLASER~ = 0, FWHM~MEGA-PRESS~ = 0, FreqShift~sLASER~ = 0, FreqShift~MEGA-PRESS~ = 0, and meanFD = 0, was 1.3 (95%\nCI [0.66, 1.95], t(26) = 3.95, p < 0.01). \n\nAmong the fixed effects, only the effect of Condition [Rest] (beta = -0.07, 95% CI [-0.11, -0.02], t(26) = -2.84, p = 0.02); and Frequency Shift (sLASER) (beta = 0.03, 95% CI [0.01, 0.06], t(26) = 2.31, p = 0.05) were statistically significant. All other predictors --- including E:I (beta = 0.07, 95% CI [-0.05, 0.19], t(26) = 1.12, p = 0.28); \nalong with FWHM~MEGA-PRESS~ (beta = 0.01, 95% CI [-0.05, 0.07], t(26) = 0.28, p = 0.78); \nFWHM~sLASER~ (beta = -0.02, 95% CI [-0.09, 0.05], t(26) = -0.58, p = 0.57); \nFreqShift~MEGA-PRESS~ (beta = 0.03, 95% CI [-0.01, 0.06], t(26) = 1.56, p = 0.14);\nFreqShift~sLASER~ (beta = 0.03, 95% CI [0.01, 0.06], t(26) = 2.31, p = 0.05);\nand meanFD (beta = -0.59, 95% CI [-2.14, 0.96], t(26) = -0.75, p = 0.46) --- were not statistically significant.\n\n## Post-hoc analyses\n\nDiagnostics of our linear-mixed effects model can be found in the Supplementary Materials (@suppfig-lmemdiag; @supptbl-spearmanresults; and @supptbl-robusteffects)\n\nTo calculate the post-hoc power of our model, we required an effect size. While *in silico* and animal studies indicate that changes in E:I ratio influence the Hurst exponent [@trakoshisIntrinsicExcitationinhibitionImbalance], these models do not provide standardized effect sizes, and translation to human neuroimaging remains uncertain. Therefore, we used several effect sizes, and report here the power of each. The effect sizes we used to calculate power were: the value calculated from our model (beta = 0.07); and beta values two and three times that size: 0.14 and 0.21. \nAs a reminder, beta represents the increase of H by that amount per every increase of E:I by 1.\nThe power for these effect sizes were 25.7%, 64.2%, and 93%, respectively.\n\nFurthermore, as our spectroscopy quality metrics could be highly correlated with each other (e.g., FWHM measures from the two sequences, or frequency shifts), we checked variance inflation factors (VIFs) to ensure all values were < 5 (generally acceptable). VIFs were: EI = 1.24, Condition = 1.55, FWHMsLASER = 1.76, FWHMMEGA = 1.45, FreqShiftsLASER = 1.15, FreqShiftMEGA = 1.48, and MeanFD = 1.28.\n\nMean ± sd of the main metabolites, their Cramer-Rao lower bounds, E:I, and H during rest and movie are reported in @tbl-results. Boxplots between rest and movie can be seen in @fig-results. Neither Glx nor GABA+ were different between movie and rest conditions. E:I ratio did not change between conditions either. H was found to be greater during movie watching than rest.\n\n|                  | Rest | Movie | p-value |\n| ---------------- | ---- | ----- | ------- |\n| **Glx**    | 9.84 ± 1.06 | 10.04 ± 0.79  | 0.26 |\n| **GABA+**  | 5.48 ± 0.77 | 5.23 ± 0.71  | 0.17 |\n| **E:I Ratio**    | 1.82 ± 0.25 | 1.94 ± 0.25  | 0.08 |\n| **H**     | 0.98 ± 0.98 | 1.05 ± 1.05 | < 0.01 |\n\n: **Summary of main measures** Glx and GABA+ values are in millimoles. {#tbl-results}\n\n\n\n\n\n::: {#cell-fig-results .cell}\n\n```{.r .cell-code .hidden}\nlayout <- \"\n  AABB\n  CCDD\n  \"\n\nglx_boxplot + gabaplus_boxplot + ei_boxplot + hurst_boxplot + plot_layout(design = layout) + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![**Paired comparison of metabolite values during rest (green) and movie (orange) conditions.** A) Glx (mM); B) GABA+ (mM); and C) E:I. Paired dots represent the same participant across conditions. Mean difference with 95% confidence intervals, and as Cohen's D are reported at the top of each plot.](index_files/figure-docx/fig-results-1.png){#fig-results}\n:::\n:::\n\n\n\n\n\nH was not found to correlate with Glx, GABA+, or E:I, during rest or movie (@fig-correlations).\n<!-- TODO: add r to the above sentence -->\n\n\n\n\n\n::: {#cell-fig-correlations .cell}\n\n```{.r .cell-code .hidden}\nlayout <- \"\nAABB\n#CC#\n\"\nglx_hurst_plot + gabaplus_hurst_plot + ei_hurst_plot + plot_layout(design=layout, guides = 'collect', axes = 'collect', axis_titles = 'collect') + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![**Scatter plots of H vs. metabolites.** A) Glx (mM); B) GABA+ (mM); and C) E:I. Rest is in green, while movie is in orange. p-values are reported at the top of each plot.](index_files/figure-docx/fig-correlations-1.png){#fig-correlations}\n:::\n:::\n\n\n\n\n\n### Data quality\n\nMean FD was not correlated with H during rest (r = -0.33, p = 0.18) but was moderately negatively correlated with H during movie watching (r = -0.49, p = 0.04; see Supplementary Materials @suppfig-dataquality A).\n\nGlx and GABA+ were tested for associations with FWHM values during rest and movie watching. No significant correlations were found (see Supplementary Materials @suppfig-dataquality B and C). Glx and GABA+ were tested for associations with frequency shift during rest and movie watching. No significant correlations were found (see Supplementary Materials @suppfig-dataquality D and E).\n\nWater FWHM and creatine SNR (CR-SNR) for both sLASER and MEGA-PRESS were analyzed pre- vs. post-fMRI. Supplementary @supptbl-FWHMprepost, @supptbl-CRSNR, and @supptbl-FWHMCRSNR present the paired t-tests and subject-level rest/movie values, while Supplementary @suppfig-fwhmdriftplot show the individual trajectories. No systematic drifts were detected (all p > 0.2 for FWHM; p > 0.3 for SNR).\n<!-- TODO: fix table and figure reference -->\nFurthermore, a group averaged plot of the frequency shift between rest and movie can be found in the Supplementary Materials (@suppfig-frequencyshift).\n\n## Re-analysis using Gannet\n\nThe re-analysis of our results using only the MEGA-PRESS sequence and `Gannet` did not result in any significant changes from the results reported above. We have included these results in the Supplementary Material.\n\n# Discussion\n\nThis study provides the first *in vivo* human investigation of the relationship between H and the E:I ratio, measured using fMRI and MRS-derived glutamate and GABA levels, respectively. No association was observed between H and E:I, suggesting that these indices may reflect distinct dimensions of neural dynamics. During movie-watching, H increased relative to rest, consistent with stronger long-range temporal dependencies in BOLD activity during visual stimulation. In contrast, Glx, GABA+, and their ratio (E:I) remained stable across conditions. These results indicate that functional signal complexity, as indexed by H, is sensitive to sensory engagement but does not appear to covary with MRS-derived estimates of excitatory–inhibitory balance under the current experimental conditions.\n\nAn increase in H during movie-watching relative to rest aligns with previous work from our lab [@campbellFractalBasedAnalysisFMRI2022], which reported increased H in the visual network (as defined by Yeo's seven resting-state networks [@thomasyeoOrganizationHumanCerebral2011]) during movie-watching using data from the Human Connectome Project [@vanessenHumanConnectomeProject2012]. While this increase in H is consistent with our prior findings, other studies have reported decreases in H during active tasks [@heScaleFreePropertiesFunctional2011; @churchillSuppressionScalefreeFMRI2016; @ciuciuInterplayFunctionalConnectivity2014; @barnesEndogenousHumanBrain2009]. The current results therefore suggest that the naturalistic, passive nature of movie-watching elicits a different effect on H compared to more active tasks. This interpretation is consistent with evidence indicating distinct neural responses and BOLD signal characteristics between conventional active visual tasks and naturalistic passive visual stimuli [@campbellFractalBasedAnalysisFMRI2022; @hassonReliabilityCorticalActivity2010]. Higher H during movie-watching may reflect richer scaling properties that support the continuous integration of visual stimuli [@campbellFractalBasedAnalysisFMRI2022].\n\nNo significant changes were observed in either Glx or GABA+ between conditions. Consequently, the E:I ratio remained stable. The experimental design included both resting and movie-watching conditions to induce measurable differences in H, Glx, and GABA+, providing a wider range of values to test for correlations between these metrics. However, the absence of condition-related differences in Glx and GABA+ complicates interpretation of the null findings. Establishing such changes would have provided a foundation for directly examining the correlation between H and the E:I ratio. Without clear evidence that the paradigm elicited detectable neurochemical variation, it remains uncertain whether the lack of association between H and E:I reflects a genuine independence of these measures or limited sensitivity of the MRS protocol to capture subtle metabolic changes.\n\nA recent meta-analysis of studies measuring Glu and Glx [@pasantaFunctionalMRSStudies2023] reported a minimal task-induced increase in Glu and Glx within the visual cortex, primarily in the context of pain, learning, or motor paradigms rather than visual stimulation. Additionally, many of the studies included were conducted at 7T, offering increased sensitivity for detecting changes in Glu and Glx. Nonetheless, several studies have demonstrated changes in Glu and Glx at 3T [@gutzeitDifferentialNMRSpectroscopy2013; @cleveAssessmentIntraInterregional2017; @apsvalkaEventrelatedDynamicsGlutamate2015]. Regarding our GABA+ findings, the same meta-analysis [@pasantaFunctionalMRSStudies2023] reported no task-dependent change in GABA within the visual cortex. This may be attributable to technical difficulties associated with capturing GABA levels using MRS at 3T due to its low concentration and spectral overlap with more abundant metabolites [@pasantaFunctionalMRSStudies2023]. Although, several studies have successfully reported changes in GABA at 3T using different paradigms and/or regions of interest [@floyer-leaRapidModulationGABA2006; @sampaio-baptistaChangesFunctionalConnectivity2015; @staggRoleGABAHuman2011].\n\nAnother reason changes in Glx or GABA+ may not have been observed could be due to our use of a block-design: collecting 24 minutes of rest data, then collecting 24 minutes of movie-watching data. While a block design has the advantage of a more robust metabolite quantification due to greater signal averaging, brain homeostatis during these long blocks may lead to an erasure of any real metabolic changes [@mangiaMetabolicPathwaysActivitydependent2012; @apsvalkaEventrelatedDynamicsGlutamate2015]. Indeed, Pasanta et al. (2023) [@pasantaFunctionalMRSStudies2023] and Archibald et al. (2020) [@archibaldMetaboliteActivityAnterior2020] reported larger metabolite changes during event-related paradigms compared to block designs, underscoring how task timing and structure can strongly influence the detectability of metabolic modulation with MRS.\n\nThe concept of E:I balance encompasses multiple biological scales and mechanisms beyond neurotransmitter concentrations, including the relative densities of excitatory and inhibitory neurons, synaptic properties, interneuron subtype interactions, and electrophysiological signatures such as 1/f spectral scaling. While the glutamate-to-GABA ratio measured via MRS provides a noninvasive --- albeit indirect --- estimate of neurochemical E:I balance in humans, it remains a simplification of the underlying complexity. MRS derived values reflect total glutamate and GABA metabolite pools, predominantly intracellular and metabolically active, rather than direct synaptic neurotransmitter release underlying real-time excitation and inhibition. Moreover, conventional MRS measures such as Glx and GABA+ include contributions from glutamine and macromolecules, respectively, limiting their chemical specificity. Therefore, while these metabolites serve as useful proxies related to excitatory and inhibitory neural systems, caution is warranted when interpreting them as direct indices of neurotransmission. Nonetheless, these metabolic pools provide valuable insight into the overall balance of excitation and inhibition within the brain’s microenvironment and remain widely used in human *in vivo* studies of neural function and dysfunction. Finally, few studies have directly quantified both glutamate and GABA in the same individuals, highlighting the novelty and importance of this approach. Our study acknowledges these limitations and aims to provide a step toward linking neurochemical measures with large-scale brain dynamics related to criticality.\n\nAlternatively, the present findings may in fact indicate that H and E:I are not directly coupled, or that their relationship is more complex than a simple linear association. This would perhaps not be surprising given the large disparity of findings in the literature, especially with regard to the directionality and linearity of the proposed E:I-Hurst relationship [@liangExcitationInhibitionBalance2024; @poilCriticalStateDynamicsAvalanches2012; @lombardiBalanceExcitationInhibition2017; @baumgartenCriticalExcitationinhibitionBalance2019; @bruiningMeasurementExcitationinhibitionRatio2020; @trakoshisIntrinsicExcitationinhibitionImbalance; @gaoInferringSynapticExcitation2017] (see @tbl-lit). \nThe heterogeneity across these studies underscores the challenges of studying this phenomenon and suggests that any potential E:I-Hurst relationship may depend on experimental context, data acquisition methods, or analysis strategies. Further work is needed to clarify the true nature of this relationship and the conditions under which it might emerge.\n\n| Citation | Study Type | H Data Type | H Calculation Method | E:I Type | E:I-Hurst Relationship |\n| ------------- | -------------- | -------------- | ------------- | -------------- | -------------- |\n| Poil et al. (2012)@poilCriticalStateDynamicsAvalanches2012 | Computational with in-house simulated model | Neuronal avalanche size | Detrendend fluctuation analysis (DFA) | Structural: number of E-to-I neurons | Inverse U |\n| Bruining et al. (2020)@bruiningMeasurementExcitationinhibitionRatio2020 | Computational with model by Poil et al. (2012); modified in-house | Neuronal oscillation amplitude | DFA | Structural: number of E-to-I synapses | Inverse U |\n| Gao et al. (2017)@gaoInferringSynapticExcitation2017 | Computational; in vivo in rats and macaques | Local field potential (LFP) | PSD | Estimated from LFP | Positive linear |\n| Lombardi et al. (2017)@lombardiBalanceExcitationInhibition2017 | Computational with in-house model | Neuronal avalanche size | PSD | Structural: number of E-to-I neurons | Negative linear |\n| Trakoshis et al. (2020)@trakoshisIntrinsicExcitationinhibitionImbalance | Computational with simulated data; in vivo in mice | fMRI BOLD signal | Wavelet-based maximum likelihood method | E-to-I synaptic conductance | Negative linear |\n\n: **Summary of methods for existing E:I-Hurst studies** {#tbl-lit}\n\nOur findings specifically show an absence of a robust association between the Hurst exponent and MRS-derived E:I ratio, challenging the assumption that these measures directly reflect a shared underlying mechanism, such as the brain’s distance from criticality. One possibility is that while both H and E:I may independently vary with neural excitability, their relationship is nonlinear or not detectable at the temporal and spatial scales of fMRI and MRS. Additionally, the E:I balance estimated via glutamate and GABA concentrations may reflect metabolic rather than synaptic activity, limiting its correspondence with network dynamics captured by BOLD signal autocorrelation. These results have important implications for studies that use H as a proxy for E:I, particularly in neurodevelopmental or neurodegenerative contexts, and suggest caution in interpreting H as a stand-in for neurochemical balance without direct validation. Future research should investigate whether the relationship emerges under task-driven conditions, in specific brain regions, or in populations with pronounced E:I dysregulation.\n\nFinally, it is also possible that while an E:I-Hurst relationship exists, it is not observed within the visual cortex. This theory seems plausible given that MRS studies of disrupted E:I, mostly conducted within the context of autistic adults, have found changes in E:I within other brain regions such as the anterior cingulate cortex, frontal lobe, or temporal lobe [@ajramContribution1HMagnetic2019]. Moreover, findings with reference to changes in excitatory or inhibitory neurotransmitters within the visual cortex tend to be difficult to capture, perhaps indicating that E:I shows less changes in this region [@pasantaFunctionalMRSStudies2023]. However, this would suggest that the E:I-H relationship would be region dependent, and therefore not a global theory as it is often portrayed.\n\nAs both H and E:I have been known to change with age, we did not seek to limit our sample to any specific age range. Furthermore, other physiological details --- such as caffeine, nicotine, phase of the menstrual cycle, gender, and medication use --- were not collected, as the core E:I-Hurst theory posits a global relationship that should hold irrespective of specific brain states or transient physiological factors. Additionally, our within-subjects design strengthens this approach: our core analyses assessing changes between resting state and movie-watching were paired, with each participant serving as their own control. This reduces the influence of inter-individual variability, including age-related and other brain-state effects.\n\n## Limitations and Strengths\n\nBeyond the limitations already mentioned (field strength, visual cortex, passive task, block design), another limitation was our small sample size. As this was a pilot study, 26 participants were initially scanned. Once individuals were excluded for poor MRI quality, only 18 participants' data were analyzed. With this small sample size, it is difficult to make conclusions about a concept as complex as the E:I-Hurst relationship. \n\n<!-- TODO: the next three sentences are a repeat from above... don't need twice... -->\nIt is also important to note that MRS measures reflect total glutamate and GABA metabolite pools, predominantly intracellular and involved in metabolic processes, rather than direct synaptic neurotransmitter release. Furthermore, commonly used measures such as Glx and GABA+ include signals from glutamine and macromolecules, respectively, limiting their chemical specificity. Therefore, while these metabolites serve as useful proxies related to excitatory and inhibitory neural systems, caution is warranted when interpreting them as direct indices of neurotransmission. Nonetheless, these metabolic pools provide valuable insight into the overall balance of excitation and inhibition within the brain's microenvironment and remain widely used in human *in vivo* studies of neural function and dysfunction. Although voxel placement was guided by anatomical landmarks and performed by trained personnel, some variability in voxel location across subjects and sessions may have introduced noise in metabolite quantification. Future studies may benefit from automated alignment and formal voxel overlap analysis to reduce this source of variability. Furthermore, our MRS voxels were placed once for the first MRS sequence, and copied for the subsequent MRS runs. This 'cloning' assumes nominal stability and does not capture any potential effective sampling differences due to head motion or shim-related changes.\nFuture studies may also wish to acquire high resolution anatomical scans before each MRS run in order to re-align the MRS voxel and to quantify: intra-subject voxel movement; voxel dice coefficient: overlap of runs (ideally >0.90); center-of-mass distance: Euclidean shift (mm) between runs (e.g. threshold >5mm outlier). \nWe did not explicitly monitor scanner frequency drift following the fMRI runs. Heating-related drift can affect the stability of MRS sequences, potentially introducing variability in glutamate and GABA quantification [@huiFrequencyDriftMR2021]. While all MRS data were visually inspected for quality, we cannot rule out subtle effects of drift, which may have contributed to noise in the E:I measurements. We included frequency drift in our linear mixed-effects models in an attempt to control for these confounds. For future research, we highly recommend prospective drift corrections to address these issues.\nFinally, the order of scanning conditions (rest followed by movie-watching) was not pseudorandomized. This may introduce potential order-related confounds, such as physiological adaptation or scanner drift, which could influence the observed differences between conditions.\n\nAn additional avenue for future research involves dynamic fMRS, which seeks to capture time-varying changes in metabolite levels during task performance. While promising, such approaches currently face substantial limitations in signal-to-noise ratio and temporal resolution, particularly for edited GABA measures. Our study was not optimized for dynamic fitting, but future work could explore how fluctuations in neurometabolites relate to moment-to-moment variations in BOLD signal complexity.\n\nWe hope that by future researchers can use our reported effect sizes to calculate potential sample sizes. We would also like to list some of the strengths of our study, which include: using sLASER (as opposed to PRESS), which has been shown to have enhanced detection of complex multiplets such as Glx/Glu [@wilsonMethodologicalConsensusClinical2019]; using the J-editing sequence MEGA-PRESS for improved GABA detection [@peekComprehensiveGuideMEGAPRESS2023]; using a large MRS voxel size (~22 ml) as per consensus recommendations [@peekBrainGABAGlutamate2020; @choiSpectralEditing1H2021; @linMinimumReportingStandards2021]; measuring H within the same region as our single-voxel MRS; and using multi-echo fMRI for improved motion artifact regression [@kunduMultiechoFMRIReview2017].\n\n## Lessons for Future Researchers\n\nFinally, we hope that we can provide some guidance to future researchers. The following is a non-exhaustive list of suggestions for future work: \n\n- future studies should consider using ultra-high-field 7T MRI, which provides improved spectral resolution and more reliable detection of Glu and GABA compared to conventional 3T MRI [@terpstraTestretestReproducibilityNeurochemical2016]; \n- examining paradigms that have consistently demonstrated alterations in these metabolites, such as pain studies, may enhance the likelihood of detecting changes in Glu and GABA [@archibaldMetaboliteActivityAnterior2020; @cleveAssessmentIntraInterregional2017; @gutzeitDifferentialNMRSpectroscopy2013].\n- exploring brain regions beyond the visual cortex, such as the anterior cingulate cortex, which is commonly implicated in pain processing [@archibaldMetaboliteActivityAnterior2020; @mullinsNovelTechniqueStudy2005; @gussewTimeresolvedFunctional1H2010; @gutzeitInsulaspecificResponsesInduced2011];\n- including a more diverse participant sample --- beyond healthy controls --- may help capture a wider range of H and E:I values, potentially improving sensitivity to metabolite-related changes;\n- increasing sample size in order to detect small effect sizes;\n- using an event-related design, as opposed to the block design we used, may provide more sensitivity to detecting rapid and transient neural responses due to its ability to isolate specific events within the scan session [@mullinsTheoryFunctionalMagnetic2018]. However, see Pasanta et al. (2023) [@pasantaFunctionalMRSStudies2023] for a longer discussion and possible downsides to this approach;\n- and finally, using a combined fMRI-MRS sequence [@ipCombinedFMRIMRSAcquires2017; @dwyerSimultaneousMeasurementBOLD2021] to measure BOLD and Glu/GABA near-simultaneously.\n\nTogether, these considerations may help in overcoming the limitations observed in the present study and contribute to a clearer understanding of the potential relationship between E:I and H.\n\n# Conclusion\n\nIn conclusion, the results do not support a relationship between H and the E:I ratio in the visual cortex either during rest or during movie-watching at 3T in humans. Although a task-related increase in H was observed, no accompanying changes were detected in Glu, GABA, or E:I between movie and rest. Comparing our findings to the broader literature, E:I balance may be too subtle to be detected with conventional 3T MRS methods [@terpstraTestretestReproducibilityNeurochemical2016]. Therefore, higher-field (7T) or multi-voxel fMRS studies would be needed to confirm. With regards to the broader E:I-Hurst relationship, we similarly suggest that either this relationship is insufficiently captured with our methods, or that the relationship between these two variables may be more complex than originally envisaged --- perhaps they are not directly related, but rather connected through other mediating variables in a non-linear fashion. To our knowledge, this is the first *in vivo* human study to test for this relationship. It is our hope that as the literature grows, more authors will examine this relationship with respect to other brain regions and using other methods, and will use the lessons learned in this study to inform their own. Hopefully then it will be possible to corroborate findings to probe the complex relationships that may exist with regards to H and E:I in the human brain.\n\n# Data availability statement {.unnumbered}\n\nAll code used in this paper is available at [github.com/WeberLab/EI_Hurst_Analysis](https://github.com/WeberLab/EI_Hurst_Analysis). The raw MRI data used in this paper is available by contacting the author. The manuscript was written in a 'reproducible manner': the entire manuscript, including statistics reported, figures, and tables, can be reproduced here: [weberlab.github.io/EI_Hurst_Manuscript/](https://weberlab.github.io/EI_Hurst_Manuscript/)\n\n# Competing interests {.unnumbered}\n\nThe authors declare they have no known competing interests.\n\n# Author contributions {.unnumbered}\n\nLS performed data curation, formal analysis, investigation, software, visualization, and wrote the original draft. \nJA helped with validation, visualization, and reviewed and edited the manuscript.\nAMW was responsible for conceptualization, data curation, formal analysis, funding acquisition, investigation, methodology, project administration, resources, supervision, validation, visualization, and writing - review & editing.\n\n# Acknowledgements {.unnumbered}\n\nThe work presented in this paper was supported in part from funding from the British Columbia Children's Hospital Foundation, and an NSERC Discovery Grant.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n\\newpage\n\n# Supplementary Material {.appendix .unnumbered}\n\n## MRS quality {.unnumbered}\n\nA summary of MRS quality, such as water FWHM, Cr SNR, and frequency shift are provided in @supptbl-quality.\n\n::: {#supptbl-quality}\n| Measure | Rest sLASER | Rest MEGA-PRESS | Movie sLASER | Movie MEGA-PRESS |\n|---|---|---|---|---|\n| water FWHM (Hz) | 8.47 ± 0.66 | 7.86 ± 0.8 | 8.32 ± 0.72 | 7.95 ± 0.82 |\n| Cr SNR | 147.61 ± 20.46 | 101.05 ± 21.42 | 140.6 ± 26 | 98.75 ± 20.01 |\n| Frequency Shift (ppm) | -3.08 ± 0.81 | -3.98 ± 0.94 | -3.12 ± 0.76 | -3.85 ± 1.05 |\n\n**Summary of spectroscopy quality measures.** FWHM = full-width half-maximum; Cr = creatine; SNR = signal-to-noise ratio.\n:::\n\nA summary of voxel placement statistics are provided in @supptbl-singlevoxel.\n\n::: {#supptbl-singlevoxel}\n| Measure | Amount |\n| --- | --- |\n| Voxel Rotation (degrees) | -39 ± 8.13 |\n| GM Tissue Fraction | 0.64 ± 0.04 |\n| WM Tissue Fraction | 0.24 ± 0.04 |\n| CSF Tissue Fraction | 0.12 ± 0.03 |\n\n**Summary of spectroscopy voxel placement values** GM = grey matter; WM = white matter; CSF = cerebrospinal fluid.\n:::\n\n## Linear-mixed effects model diagnostics {.unnumbered}\n\nLinear-mixed effects model diagnostics are provided in @suppfig-lmemdiag.\n\n::: {#suppfig-lmemdiag}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlayout <- \"\n  AAA\n  BBB\n  CCC\n  \"\n\nmodelresiduals_plot + modelhistresiduals_plot + modelqqnorm_plot + plot_layout(design = layout) + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-10-1.png)\n:::\n:::\n\n\n\n\n**Linear-mixed effects model tests for normality.** Model diagnostics for the linear mixed effects model predicting Hurst exponent from the EI ratio. A) Residuals vs. fitted values showing homoscedasticity. B) Histogram of residuals. C) Q-Q plot indicating normally distributed residuals.\n:::\n\nWe report Spearman correlations between E:I and H within each condition (@supptbl-spearmanresults). Spearman rho values were modest and negative (Movie: $\\rho$ = -0.3, p = 0.23; Rest: $\\rho$ = -0.12, p = 0.62), and consistent with the primary analyses in direction but not statistically significant.\n\n::: {#supptbl-spearmanresults}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nknitr::kable(spearman_results, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Condition | spearman_ei_hurst| p_value|\n|:---------|-----------------:|-------:|\n|Movie     |            -0.300|   0.225|\n|Rest      |            -0.125|   0.621|\n\n\n:::\n:::\n\n\n\n\nSpearman correlation between EI and Hurst by condition.\n:::\n\nWe also refit the linear mixed-effects model after removing the top/bottom 10% of observations in E:I, in H, and in the intersection of both (@supptbl-robusteffects). Across these trimmed datasets, the E:I fixed-effect estimate remained small and its 95% confidence interval continued to include zero, indicating that the primary conclusion is not driven by extreme values in either E:I or H. Trimming was performed on the pooled long-format dataset (rest and movie rows) to match the model specification.\n\nTaken together with the non-parametric Spearman correlations (@supptbl-spearmanresults), these analyses indicate that the E:I–H association is weak in this pilot dataset and that our primary inference (a small effect with confidence intervals spanning zero) is unchanged under non-parametric estimation and reasonable exclusion of potential outliers.\n\n::: {#supptbl-robusteffects}\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nknitr::kable(robust_effects, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Model                             | Estimate|    SE| CI_low| CI_high|\n|:---------------------------------|--------:|-----:|------:|-------:|\n|Full sample                       |    0.068| 0.061| -0.052|   0.188|\n|Trimmed EI (10–90%)               |    0.010| 0.125| -0.236|   0.256|\n|Trimmed Hurst (10–90%)            |    0.018| 0.045| -0.070|   0.107|\n|Trimmed EI & Hurst (intersection) |    0.081| 0.112| -0.139|   0.300|\n\n\n:::\n:::\n\n\n\n\nEI fixed-effect estimates (Estimate ± 95% CI) for the full sample and each trimmed sample.\n:::\n\n## Metabolites {.unnumbered}\n\n### sLASER {.unnumbered}\n\nAll metabolite concentrations and Cramer-Rao lower bounds from semi-LASER are reported in @supptbl-metabolites.\n\n::: {#supptbl-metabolites}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nslaserfullresults %>% select(Mean_SD, restcrlb, Movie, moviecrlb) %>% rename(\"Rest Conc\" = Mean_SD, \"Rest CRLB\" = restcrlb, \"Movie Conc\" = Movie, \"Movie CRLB\" = moviecrlb) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|       |Rest Conc    |Rest CRLB       |Movie Conc   |Movie CRLB      |\n|:------|:------------|:---------------|:------------|:---------------|\n|Asc    |0.34 ± 0.29  |239.72 ± 364.52 |0.34 ± 0.24  |194.39 ± 307.8  |\n|Asp    |3.49 ± 0.44  |9.56 ± 1.34     |3.39 ± 0.43  |9.72 ± 1.81     |\n|Cr     |2.04 ± 0.62  |16.33 ± 7.65    |2.1 ± 0.49   |15.22 ± 5.25    |\n|GABA   |0.69 ± 0.41  |52.78 ± 30.69   |0.67 ± 0.32  |49.06 ± 28.51   |\n|GPC    |0.92 ± 0.11  |12.11 ± 4.83    |0.9 ± 0.11   |13.56 ± 4.23    |\n|GSH    |1.3 ± 0.18   |7.61 ± 1.38     |1.32 ± 0.13  |7.44 ± 1.04     |\n|Gln    |2.82 ± 0.58  |10.11 ± 1.78    |2.93 ± 0.47  |9.72 ± 1.02     |\n|Glu    |7.02 ± 0.71  |4.33 ± 0.49     |7.11 ± 0.62  |4.17 ± 0.51     |\n|mI     |4.77 ± 0.34  |3 ± 0           |4.8 ± 0.29   |3 ± 0           |\n|Lac    |0.32 ± 0.13  |62.78 ± 38.94   |0.28 ± 0.16  |182.33 ± 311.77 |\n|NAA    |11.88 ± 1.11 |1.94 ± 0.24     |11.83 ± 1.03 |1.83 ± 0.38     |\n|NAAG   |0 ± 0        |999 ± 0         |0.07 ± 0.22  |890.78 ± 314.99 |\n|PCh    |0.16 ± 0.12  |292.5 ± 394.55  |0.18 ± 0.1   |179.89 ± 299.51 |\n|PCr    |5.68 ± 0.84  |5.83 ± 1.04     |5.7 ± 0.69   |6.11 ± 1.23     |\n|PE     |1.67 ± 0.49  |31.28 ± 11.85   |1.71 ± 0.53  |29.5 ± 8.58     |\n|sI     |0.13 ± 0.12  |198.61 ± 369.4  |0.13 ± 0.11  |127.56 ± 244.45 |\n|Tau    |1.63 ± 0.35  |15.44 ± 3.2     |1.65 ± 0.3   |15.06 ± 3.23    |\n|CrCH2  |0.26 ± 0.28  |433.94 ± 469.27 |0.24 ± 0.2   |285.11 ± 397.57 |\n|tCho   |1.07 ± 0.09  |3.72 ± 0.46     |1.07 ± 0.09  |3.56 ± 0.62     |\n|tCr    |7.72 ± 0.41  |1.44 ± 0.51     |7.8 ± 0.37   |1.39 ± 0.5      |\n|tNAA   |11.88 ± 1.11 |1.94 ± 0.24     |11.91 ± 1.04 |1.83 ± 0.38     |\n|Glx    |9.84 ± 1.06  |4.39 ± 0.5      |10.04 ± 0.79 |4.17 ± 0.51     |\n|Lip13a |18.63 ± 7.85 |76.06 ± 230.43  |20 ± 7.47    |21.78 ± 6.48    |\n|Lip13b |0.07 ± 0.3   |944.39 ± 231.7  |0 ± 0        |999 ± 0         |\n|Lip09  |4.91 ± 2.05  |25 ± 9.44       |5.22 ± 2.04  |27 ± 10.96      |\n|MM09   |3.1 ± 2.15   |112.67 ± 226.41 |3.03 ± 1.5   |103.56 ± 227.35 |\n|Lip20  |3.64 ± 1.34  |15.5 ± 4.26     |4.05 ± 1     |14.44 ± 3.07    |\n|MM20   |3.88 ± 3.43  |242.11 ± 383.63 |3.41 ± 2.16  |143 ± 262.51    |\n|MM12   |0.95 ± 0.93  |316.28 ± 389.01 |0.99 ± 0.97  |333.78 ± 425.72 |\n|MM14   |4.45 ± 2.14  |34.39 ± 21.5    |5.11 ± 2.63  |35.67 ± 25.59   |\n|MM17   |2.56 ± 1.84  |246.39 ± 414.02 |2.69 ± 1.1   |39.89 ± 31.22   |\n\n\n:::\n:::\n\n\n\n\n**All metabolite concentrations and Cramer-Rao lower bounds from semi-LASER.** Concentration values are in millimoles; Cramer-Rao lower bounds are in percentages. Conc = concentration; CRLB = Cramer-Rao lower bounds.\n:::\n\n### MEGA-PRESS {.unnumbered}\n\nAll metabolite concentrations and Cramer-Rao lower bounds from J-edited MEGA-PRESS are reported in @supptbl-megapressmetabs.\n\n::: {#supptbl-megapressmetabs}\n\n\n\n\n::: {.cell tbl-cap=''}\n\n```{.r .cell-code .hidden}\nmegapressfullresults %>% select(Mean_SD, restcrlb, Movie, moviecrlb) %>% rename(\"Rest Conc\" = Mean_SD, \"Rest CRLB\" = restcrlb, \"Movie Conc\" = Movie, \"Movie CRLB\" = moviecrlb) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|         |Rest Conc    |Rest CRLB      |Movie Conc   |Movie CRLB   |\n|:--------|:------------|:--------------|:------------|:------------|\n|GABA     |1.64 ± 0.36  |16.61 ± 5.51   |1.55 ± 0.43  |18.5 ± 5.86  |\n|GSH      |2.41 ± 0.6   |4.72 ± 0.57    |2.17 ± 0.62  |5.06 ± 0.94  |\n|Gln      |2.59 ± 0.95  |74.56 ± 230.78 |2.4 ± 0.56   |24.11 ± 9.54 |\n|Glu      |12.41 ± 1.76 |4.06 ± 0.64    |12.11 ± 1.65 |4.33 ± 0.77  |\n|NAA      |16.47 ± 1.49 |9.94 ± 2.21    |16.29 ± 2.01 |10.39 ± 1.5  |\n|NAAG     |1.8 ± 0.57   |16.61 ± 5.51   |2.02 ± 1.07  |18.5 ± 5.86  |\n|tNAA     |18.27 ± 1.41 |4.72 ± 0.57    |18.31 ± 1.65 |5.06 ± 0.94  |\n|Glx      |15 ± 1.51    |74.56 ± 230.78 |14.51 ± 1.57 |24.11 ± 9.54 |\n|MM09     |3.84 ± 0.77  |4.06 ± 0.64    |3.69 ± 0.49  |4.33 ± 0.77  |\n|GABAplus |5.48 ± 0.77  |9.94 ± 2.21    |5.23 ± 0.71  |10.39 ± 1.5  |\n\n\n:::\n:::\n\n\n\n\n**All metabolite concentrations and Cramer-Rao lower bounds from J-edited MEGA-PRESS.** Concentration values are in millimoles; Cramer-Rao lower bounds are in percentages. Conc = concentration; CRLB = Cramer-Rao lower bounds.\n::: \n\n\\newpage\n\n## Data quality {.unnumbered}\n\nData quality correlations for Hurst with mean framewise displacement, Glx and GABA+ with FWHM, and Glx and GABA+ with frequency shift are shown in @suppfig-dataquality.\n\n::: {#suppfig-dataquality}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlayout = \"\n  AAA\n  BBB\n  BBB\n  CCC\n  CCC\n  \"\n\nfree(meanfd_hurst_plot)+ free(glxandgabaplus_FWHM_plot) + free(glxandgabaplus_freqshift_plot) +\n  plot_layout(design = layout) +\n  plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-15-1.png)\n:::\n:::\n\n\n\n\n**Data quality correlations.** A) Correlation plots of H vs. mean FD (mm) for rest (green) and movie (orange). B) and C) Correlation plots of Glx (B) and GABA+ (C) vs. water FWHM (Hz) for rest (green) and movie (orange). D) and E) Correlation plots of Glx (B) and GABA+ (C) vs. frequency shift (ppm) for rest (green) and movie (orange).\n:::\n\nRest vs movie FWHM comparisons (paired t-tests) are provided in @supptbl-FWHMprepost.\n\n::: {#supptbl-FWHMprepost}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nnames(fwhm_tests) <- c(\"Seq\", \"m. rest\", \"m. movie\", \"m. diff\", \"sd diff\", \"t\", \"p\", \"CIlow\", \"CIhigh\")\nknitr::kable(fwhm_tests, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Seq    | m. rest| m. movie| m. diff| sd diff|     t|    p| CIlow| CIhigh|\n|:------|-------:|--------:|-------:|-------:|-----:|----:|-----:|------:|\n|MEGA   |    7.86|     7.95|    0.09|    0.51|  0.75| 0.46| -0.16|   0.34|\n|sLASER |    8.47|     8.32|   -0.15|    0.49| -1.28| 0.22| -0.39|   0.10|\n\n\n:::\n:::\n\n\n\n\nRest vs. movie FWHM comparison (paired t-tests) for each spectroscopy sequence. Seq = sequence; m. = mean; sd = standard deviation; t = t-value; p = p-value; CIlow = lower confidence interval; CIhigh = higher confidence interval.\n:::\n\nRest vs movie FWHM comparisons (paired t-tests) are provided in @supptbl-CRSNR.\n\n::: {#supptbl-CRSNR}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nnames(snr_tests) <- c(\"Seq\", \"m. rest\", \"m. movie\", \"m. diff\", \"sd diff\", \"t\", \"p\", \"CIlow\", \"CIhigh\")\nknitr::kable(snr_tests, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Seq    | m. rest| m. movie| m. diff| sd diff|     t|    p|  CIlow| CIhigh|\n|:------|-------:|--------:|-------:|-------:|-----:|----:|------:|------:|\n|MEGA   |  101.05|    98.75|   -2.30|    9.39| -1.04| 0.31|  -6.97|   2.36|\n|sLASER |  147.61|   140.60|   -7.01|   22.84| -1.30| 0.21| -18.37|   4.34|\n\n\n:::\n:::\n\n\n\n\nRest vs. movie CR-SNR comparison (paired t-tests) for each spectroscopy sequence. Seq = sequence; m. = mean; sd = standard deviation; t = t-value; p = p-value; CIlow = lower confidence interval; CIhigh = higher confidence interval.\n:::\n\nSubject-level FWHM and CR-SNR values for each sequence (Rest, Movie, and Movie–Rest difference) are provided in @supptbl-FWHMCRSNR.\n\n::: {#supptbl-FWHMCRSNR}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nnames(drift_table) <- c(\"Sub\", \"Seq\", \"R FWHM\", \"M FWHM\", \"Diff FWHM\", \"R SNR\", \"M SNR\", \"Diff SNR\")\nknitr::kable(drift_table, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| Sub|Seq    | R FWHM| M FWHM| Diff FWHM|  R SNR|  M SNR| Diff SNR|\n|---:|:------|------:|------:|---------:|------:|------:|--------:|\n|   1|sLASER |   8.36|   8.04|     -0.33| 135.58| 125.26|   -10.32|\n|   1|MEGA   |   7.38|   7.41|      0.03|  91.29|  92.46|     1.17|\n|   2|sLASER |   8.57|   7.72|     -0.85| 128.76| 147.92|    19.16|\n|   2|MEGA   |   7.73|   7.15|     -0.58|  82.16|  84.05|     1.89|\n|   4|sLASER |   8.61|   8.93|      0.31| 162.00| 132.33|   -29.67|\n|   4|MEGA   |   9.23|   8.56|     -0.66|  98.51| 103.83|     5.31|\n|   6|sLASER |   8.01|   7.94|     -0.06| 130.77| 152.24|    21.47|\n|   6|MEGA   |   7.35|   7.58|      0.23| 128.02| 122.19|    -5.83|\n|   7|sLASER |   9.08|   9.10|      0.02| 112.42|  99.45|   -12.97|\n|   7|MEGA   |   9.17|   8.95|     -0.22|  75.46|  84.31|     8.85|\n|   9|sLASER |   8.27|   8.53|      0.26| 172.88| 161.56|   -11.32|\n|   9|MEGA   |   8.02|   8.51|      0.49| 115.78| 108.07|    -7.71|\n|  10|sLASER |   7.65|   7.46|     -0.20| 168.43| 173.85|     5.41|\n|  10|MEGA   |   6.66|   7.20|      0.55| 115.75| 103.79|   -11.96|\n|  11|sLASER |   9.53|   8.57|     -0.96| 157.59| 136.11|   -21.48|\n|  11|MEGA   |   7.73|   8.83|      1.10| 101.11|  87.58|   -13.52|\n|  12|sLASER |   8.39|   7.79|     -0.60| 180.44| 136.71|   -43.73|\n|  12|MEGA   |   7.46|   7.43|     -0.03| 113.05| 112.73|    -0.32|\n|  13|sLASER |   7.73|   8.45|      0.72| 158.00| 207.77|    49.78|\n|  13|MEGA   |   7.06|   7.09|      0.03| 147.40| 147.57|     0.17|\n|  15|sLASER |   9.27|   8.25|     -1.03| 161.54| 135.97|   -25.57|\n|  15|MEGA   |   7.93|   7.40|     -0.53| 105.05| 124.51|    19.47|\n|  16|sLASER |   9.23|   9.19|     -0.04| 155.48| 135.41|   -20.07|\n|  16|MEGA   |   8.32|   8.29|     -0.03| 102.73|  97.17|    -5.55|\n|  18|sLASER |   8.57|   8.33|     -0.24| 116.65| 117.28|     0.62|\n|  18|MEGA   |   7.91|   7.51|     -0.40|  75.65|  83.37|     7.71|\n|  19|sLASER |   8.39|   8.57|      0.18| 169.98| 145.07|   -24.92|\n|  19|MEGA   |   7.63|   8.01|      0.37| 126.17| 107.86|   -18.31|\n|  20|sLASER |   7.94|   7.93|      0.00| 146.29| 156.69|    10.40|\n|  20|MEGA   |   7.16|   8.24|      1.08| 100.81|  85.99|   -14.82|\n|  22|sLASER |   9.51|   9.86|      0.35| 121.74|  96.63|   -25.11|\n|  22|MEGA   |   9.20|   9.43|      0.24|  60.44|  60.70|     0.26|\n|  24|sLASER |   7.18|   6.67|     -0.50| 138.38| 121.95|   -16.43|\n|  24|MEGA   |   6.73|   6.44|     -0.29|  85.78|  83.25|    -2.53|\n|  26|sLASER |   8.12|   8.42|      0.31| 140.13| 148.61|     8.48|\n|  26|MEGA   |   8.76|   9.03|      0.27|  93.80|  88.04|    -5.76|\n\n\n:::\n:::\n\n\n\n\nSubject-level FWHM and CR-SNR values for each sequence (Rest, Movie, and Movie–Rest difference). Sub = Subject; Seq = Sequence; R = Rest; M = Movie; Diff = Difference.\n:::\n\nPlots of individual water FWHM changes between rest and movie-watching conditions for both MEGA-PRESS and sLASER are shown in @suppfig-fwhmdriftplot.\n\n::: {#suppfig-fwhmdriftplot}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nfwhm_drift_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-19-1.png)\n:::\n:::\n\n\n\n\nPlots of individual water full-width half-maximum changes between rest and movie-watching conditions for both MEGA-PRESS and sLASER\n:::\n\nFrequency shift between rest and movie are shown in @suppfig-frequencyshift.\n\n::: {#suppfig-frequencyshift}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlayout = \"\n  A\n  B\n  \"\nfreqshiftslaser_plot <- image_read(\"./Data/slaser_scatter.png\")\nfreqshiftslaser_plot_dim <- image_info(freqshiftslaser_plot)\nfreqshiftslaser_plot <- ggplot() + background_image(freqshiftslaser_plot) + theme_void()\n\nfreqshiftmegapress_plot <- image_read(\"./Data/megapress_scatter.png\")\nfreqshiftmegapress_plot_dim <- image_info(freqshiftmegapress_plot)\nfreqshiftmegapress_plot <- ggplot() + background_image(freqshiftmegapress_plot) + theme_void()\n\np1 <- free(freqshiftslaser_plot) + free(freqshiftmegapress_plot) +\n  plot_layout(design = layout)\n\np1 + plot_annotation(tag_levels = \"A\") + theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-20-1.png)\n:::\n:::\n\n\n\n\n**Frequency shift between rest and movie.** Overlay of all participants' frequency drift (ppm) plots during rest (blue) and movie (red) for A) semi-LASER and B) MEGA-PRESS. Note, the GE semi-LASER sequence averaged all transients (128) into groups of 4, each with 32 transients, before being saved as raw P-file.\n:::\n\n\\newpage\n\n## Gannet Results {.unnumbered}\n\nAn example fit result from Gannet of a subject at rest is shown in @suppfig-gannet.\n\n![**Gannet Fit.** Sample Gannet fit result from a subject a rest. Glx (3.75ppm) and GABA (3) data (blue) and model fit (red) are shown top left. Water and creatine reference signals are shown bottom left. Table on right shows GABA+ and Glx values before tissue-correction.](./Data/megapress/sub-Pilot01/rest_gannet/GannetFit_output/P38912_vox1_fit.png){#suppfig-gannet}\n\nTo examine the relationship between H and E:I, we ran a linear mixed-effects model. \nThe model's total explanatory power was substantial (conditional r^2^ = 0.64), with fixed effects (marginal r^2^) equal to 0.23. The model's intercept, corresponding to EI = 0, Condition = Movie, FWHM~MEGA-PRESS~ = 0, FreqShift~MEGA-PRESS~ = 0, and meanFD = 0, was 1.2 (95%\nCI [0.66, 1.7], t(26) = 4.64, p < 0.01). \nWithin this model, only the effect of Condition [Rest] was statistically significant (beta = -0.08, 95% CI [-0.13, -0.03], t(26) = -3.32, p < 0.01). \nThe effect of E:I was statistically non-significant (beta = -0.07, 95% CI [-0.21, 0.06], t(26) = -1.04, p = 0.31); \nalong with FWHM~MEGA-PRESS~ (beta = 0.03, 95% CI [-0.03, 0.08], t(26) = 0.96, p = 0.35); \nFreqShift~MEGA-PRESS~ (beta = 0.01, 95% CI [-0.02, 0.05], t(26) = 0.63, p = 0.53);\nand meanFD (beta = -0.76, 95% CI [-2.34, 0.82], t(26) = -0.95, p = 0.35).\n\n\nMean ± sd of metabolites and E:I when analyzed using Gannet, during rest and movie, are reported in @supptbl-gannetresults. Boxplots between rest and movie can be seen in @suppfig-gannetresults. Neither Glx nor GABA+ were different between movie and rest conditions. E:I ratio did not change between conditions either.\n\n::: {#supptbl-gannetresults}\n|                  | Rest | Movie | p-value |\n| ---------------- | ---- | ----- | ------- |\n| **Glx**    | 10.84 ± 1.06 | 10.72 ± 0.68  | 0.43 |\n| **GABA+**  | 3.59 ± 0.38 | 3.53 ± 0.36  | 0.33 |\n| **E:I Ratio**    | 1.82 ± 0.25 | 1.94 ± 0.25  | 0.08 |\n\n**Summary of main metabolite results using Gannet** \n:::\n\n::: {#suppfig-gannetresults}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlayout <- \"\n  AABB\n  #CC#\n  \"\n\ngannetglx_boxplot + gannetgaba_boxplot + gannetei_boxplot + hurst_boxplot + plot_layout(design = layout) + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Too few patch areas to hold all plots. Dropping plots\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-21-1.png)\n:::\n:::\n\n\n\n\n**Paired comparison of metabolite values analyzed using Gannet during rest (green) and movie (orange) conditions.** A) Glx (mM); B) GABA+ (mM); and C) E:I. Paired dots represent the same participant across conditions. Mean difference with 95% confidence intervals, and as Cohen's D are reported at the top of each plot.\"\n:::\n\nH was not found to correlate with Glx (Rest: r = 0, p = 0.99; Movie: r = -0.27, p = 0.28), GABA+ (Rest: r = 0.02, p = 0.93; Movie: r = 0.11, p = 0.67), or E:I (Rest: r = -0.04, p = 0.89; Movie: r = -0.32, p = 0.2) (@suppfig-gannetcorrelations).\n\n::: {#suppfig-gannetcorrelations}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlayout <- \"\nAABB\n#CC#\n\"\ngannetglx_hurst_plot + gannetgaba_hurst_plot + gannetei_hurst_plot + plot_layout(design=layout, guides = 'collect', axes = 'collect', axis_titles = 'collect') + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 11))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: annotation$theme is not a valid theme.\nPlease use `theme()` to construct themes.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-22-1.png)\n:::\n:::\n\n\n\n\n**Scatter plots of H vs. metabolites when analyzed using Gannet.** A) Glx (mM); B) GABA+ (mM); and C) E:I. Rest is in green, while movie is in orange. P-values are reported at the top of each plot.\n:::\n\nGlx estimates were not strongly correlated between sLASER and MEGA-PRESS (Rest $r = 0.06$, Movie $r = 0.25$), while mean absolute differences remained under 1 institutional units. @supptbl-glxagreement reports the paired summary statistics, and @suppfig-glxagreementplot visualises the subject-level agreement.\n\nThis finding is consistent with several studies that have directly compared Glx measured from MEGA-PRESS \"OFF\" spectra, with 'gold standard' short-TE sequences (PRESS and sLASER), which have consistently reported poor agreement [@vanveenendaalGlutamateQuantificationPRESS2018; @bellVivoGlxGlu2021; @thomsonVivoGlxMeasurements2026]. Reasons for this include the fact that MEGA-PRESS uses a longer TE time (68 ms compared to sLASER's 35 ms) [@maddockEstimatingGlutamateGlx2018]; chemical shift displacement error differences between the two sequences [@archibaldTestretestReliabilityMultimetabolite2025]; and scanner drift due to MEGA-PRESS being acquired on average 6.43 ± 1.67 (Rest) and 5.89 ± 0.95 minutes (Movie) after sLASER.\n\n::: {#supptbl-glxagreement}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nnames(glx_agreement_table) <- c(\"Cond\", \"n\", \"m. sLASER\", \"m. MEGA\", \"m. diff\", \"sd diff\", \"m.a. diff\", \"r\", \"p\", \"CIlow\", \"CIhigh\")\nknitr::kable(glx_agreement_table, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Cond  |  n| m. sLASER| m. MEGA| m. diff| sd diff| m.a. diff|    r|    p| CIlow| CIhigh|\n|:-----|--:|---------:|-------:|-------:|-------:|---------:|----:|----:|-----:|------:|\n|Movie | 18|     10.04|   10.72|   -0.67|    0.90|      0.91| 0.25| 0.31| -0.24|   0.64|\n|Rest  | 18|      9.84|   10.84|   -1.00|    1.45|      1.28| 0.06| 0.80| -0.42|   0.51|\n\n\n:::\n:::\n\n\n\n\nAgreement between sLASER- and MEGA-PRESS-derived Glx within each condition. Cond = condition; n = number of subjects; m. = mean; m.a. = mean absolute; r = Pearson correlation; p = p-value; CIlow = lower confidence interval; CIhigh = higher confidence interval.\n:::\n\n::: {#suppfig-glxagreementplot}\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nglx_agreement_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-docx/unnamed-chunk-24-1.png)\n:::\n:::\n\n\n\n\nGlx from MEGA-PRESS plotted against Glx from sLASER, during both rest (green) and movie-watching (orange). Dashed line represents perfect agreement.\n:::\n",
    "supporting": [
      "index_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}