project:
  type: manuscript
  # render: 
  #   - "*.qmd"
  #   - "!pyvenv_csvo/"
  #   - "*.ipynb"

manuscript:
  article: index.qmd

code-links:
  - repo
  - binder

execute:
  freeze: auto
  cache: false

format:
  html:
    embed-resources: true
    notebook-links: true
    toc: true
    comments:
      hypothesis: true
  # docx: default
  docx:
    reference-doc: custom-reference.docx
    line-numbers: false
  # jats: default
  nature-pdf:
    journal: 
      cite-style: sn-jnl
    cite-method: natbib
    keep-tex: true

filters:
  - parse-latex
